image: 'node'

stages:
 - test

before_script:
  - npm i

test:
  timeout: 1 hours
  allow_failure: false
  stage: test
  script:
    - npm run test-html
  artifacts:
    expire_in: 15 day
    when: always
    paths:
      - $CI_PROJECT_DIR/mochawesome-report
